# Generated by Django 4.0.4 on 2022-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_imagekeywordmodel_keywordmodel_musickeywordmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmodel',
            name='word',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
