# Generated by Django 4.0.4 on 2022-11-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_keywordmodel_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordmodel',
            name='input_num',
            field=models.IntegerField(default=0),
        ),
    ]
