# Generated by Django 4.0.4 on 2022-11-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_keywordmodel_input_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='musicuploadmodel',
            name='keyword',
        ),
    ]
