# Generated by Django 3.2 on 2022-11-16 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0008_imageuploadmodel_result_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArtUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(default='', max_length=255)),
                ('thumbnail', models.CharField(default='', max_length=255)),
                ('input_text', models.CharField(default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result_favorite', models.CharField(blank=True, max_length=255)),
                ('kind', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='musickeywordmodel',
            name='keyword_id',
        ),
        migrations.RemoveField(
            model_name='musickeywordmodel',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='musicuploadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageKeywordModel',
        ),
        migrations.DeleteModel(
            name='ImageUploadModel',
        ),
        migrations.DeleteModel(
            name='MusicKeywordModel',
        ),
        migrations.DeleteModel(
            name='MusicUploadModel',
        ),
        migrations.AddField(
            model_name='artkeywordmodel',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.artuploadmodel'),
        ),
        migrations.AddField(
            model_name='artkeywordmodel',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.keywordmodel'),
        ),
    ]
