# Generated by Django 3.2 on 2022-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20221116_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoArtUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(default='', max_length=255)),
                ('thumbnail', models.CharField(default='', max_length=255)),
                ('input_text', models.CharField(default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.IntegerField(default=0)),
            ],
        ),
    ]
