# Generated by Django 3.2 on 2022-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20221118_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='artlike',
            name='like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
